## This is for creating image from the resource we have , eg I had a html resource for a website outof which i have made a image of it.



#choosing the base image for the reference
FROM ubuntu:latest
LABEL "Author"="Asif"
LABEL "Project"="ImageOfaWebsite"

#when we build the image then it is interactive process so, we need to have the non interactive variables
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install git -y
RUN apt install apache2 unzip -y

# The CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"] instruction in a Dockerfile ensures that the Apache HTTP server starts and runs in the foreground, keeping the Docker container alive and functioning as expected.
CMD ["/usr/sbin/apache2ctl", "-D", "FORGROUND"]
EXPOSE 80
WORKDIR /var/www/html
VOLUME /var/log/apache2

#Before doing this we have the file where all file are present for the website we just have to add the file to the work directory or else we can also copy all the file inside the folder to the work
ADD Website.tar.gz /var/www/html
